//
// FILETYPE.H - File type utilities
//
// EBS - HTTP
//
// Copyright EBS Inc. , 2006
// All rights reserved.
// This code may not be redistributed in source or linkable object form
// without the consent of its author.
//
#ifndef __FILETYPE_H__
#define __FILETYPE_H__

typedef enum e_FileContentType
{
	FILE_TYPE_UNKNOWN = -1,
	FILE_TYPE_APPLICATION_ODA,
	FILE_TYPE_APPLICATION_OCTET_STREAM,
	FILE_TYPE_APPLICATION_PDF,
	FILE_TYPE_APPLICATION_POSTSCRIPT,
	FILE_TYPE_APPLICATION_X_COMPRESS,
	FILE_TYPE_APPLICATION_X_TAR,
	FILE_TYPE_APPLICATION_X_GTAR,
	FILE_TYPE_APPLICATION_X_GZIP,
	FILE_TYPE_APPLICATION_X_JAVASCRIPT,
	FILE_TYPE_APPLICATION_ZIP,
	FILE_TYPE_AUDIO_BASIC,
	FILE_TYPE_AUDIO_MID,
	FILE_TYPE_AUDIO_MPEG,
	FILE_TYPE_AUDIO_X_AIFF,
	FILE_TYPE_AUDIO_X_MPEGURL,
	FILE_TYPE_AUDIO_X_PN_REALAUDIO,
	FILE_TYPE_AUDIO_X_WAV,
	FILE_TYPE_IMAGE_BMP,
	FILE_TYPE_IMAGE_CIS_COD,
	FILE_TYPE_IMAGE_GIF,
	FILE_TYPE_IMAGE_IEF,
	FILE_TYPE_IMAGE_JPEG,
	FILE_TYPE_IMAGE_PIPEG,
	FILE_TYPE_IMAGE_PNG,
	FILE_TYPE_IMAGE_TIFF,
	FILE_TYPE_IMAGE_X_CMU_RASTER,
	FILE_TYPE_IMAGE_X_ICON,
	FILE_TYPE_IMAGE_X_PORTABLE_ANYMAP,
	FILE_TYPE_IMAGE_X_PORTABLE_BITMAP,
	FILE_TYPE_IMAGE_X_PORTABLE_GRAYMAP,
	FILE_TYPE_IMAGE_X_PORTABLE_PIXMAP,
	FILE_TYPE_IMAGE_X_RGB,
	FILE_TYPE_IMAGE_X_XBITMAP,
	FILE_TYPE_IMAGE_X_XPIXMAP,
	FILE_TYPE_IMAGE_X_XWINDOWDUMP,
	FILE_TYPE_MESSAGE_RFC822,
	FILE_TYPE_TEXT_CSS,
	FILE_TYPE_TEXT_H323,
	FILE_TYPE_TEXT_HTML,
	FILE_TYPE_TEXT_IULS,
	FILE_TYPE_TEXT_PLAIN,
	FILE_TYPE_TEXT_RICHTEXT,
	FILE_TYPE_TEXT_SCRIPTLET,
	FILE_TYPE_TEXT_TAB_SEPARATED_VALUES,
	FILE_TYPE_TEXT_VCARD,
	FILE_TYPE_TEXT_WEBVIEWHTML,
	FILE_TYPE_TEXT_X_COMPONENT,
	FILE_TYPE_TEXT_X_SETEXT,
	FILE_TYPE_TEXT_XML,
	FILE_TYPE_VIDEO_MPEG,
	FILE_TYPE_VIDEO_QUICKTIME,
	FILE_TYPE_VIDEO_X_LA_ASF,
	FILE_TYPE_VIDEO_X_MS_ASF,
	FILE_TYPE_VIDEO_X_MSVIDEO,
	FILE_TYPE_VIDEO_X_SGI_MOVIE,
	FILE_TYPE_X_WORLD_X_VRML,
	NUM_FILE_TYPES
}
FileContentType;

#ifdef __cplusplus
extern "C" {
#endif

FileContentType StrToFileContentType (const char *str);
const char     *FileContentTypeToStr (FileContentType type);

#ifdef __cplusplus
}
#endif


#endif /*__FILETYPE_H__*/
